### ISSUE TITLE
cherry pick handy patches

### ISSUE THREAD

**Issue by AntonioMeireles** [hooklift/xhyve#4]
@c4milo (Hi again!) 

while xhyve's upstream development gets sorted would you please consider getting consumed on this bindings pulls [#78](https://github.com/mist64/xhyve/pull/78) and [#79](https://github.com/mist64/xhyve/pull/79) floating on upstream xhyve as those would be, very, very handy for a few folks (i could fork if i have to, but as you're the upstream on this...). 

thanks in advance!

**Comment by c4milo** [comment]
I will merge them as soon as I can. Thanks @AntonioMeireles for the heads up!

**Comment by AntonioMeireles** [comment]
@c4milo no need to cherry-pick. a rebase over [xhyve-xyz/xhyve](github.com/xhyve-xyz/xhyve) is all that's needed.  (see #5 please)
